/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("test.vertx.java-library-conventions")
}

dependencies {
    implementation("org.seleniumhq.selenium:selenium-java:3.141.59")
    implementation("org.seleniumhq.selenium:selenium-chrome-driver:3.141.59")
    implementation("org.seleniumhq.selenium:selenium-firefox-driver:3.141.59")
    implementation("org.jsoup:jsoup:1.13.1")
    implementation("commons-io:commons-io:2.8.0")
}
