# https://hub.docker.com/r/warp10io/warp10


version: '2'
services:
    warp10-db:
        image: warp10io/warp10:2.7.1-ci
        container_name: warp10-db
        ports:
            - 8080:8080
            - 8081:8081
        volumes:
            - ./w10-data/:/data
        # restart: always

