/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test.vertx.app;

import io.vertx.config.ConfigRetriever;
import io.vertx.config.ConfigRetrieverOptions;
import io.vertx.config.ConfigStoreOptions;
import io.vertx.core.DeploymentOptions;
import io.vertx.core.Vertx;
import io.vertx.core.http.HttpServer;
import io.vertx.core.json.JsonObject;

public class App {
    public static void main(String[] args) {
        Vertx vertx = Vertx.vertx();

        ConfigStoreOptions fileStore = new ConfigStoreOptions()
            .setType("file")
            .setConfig(new JsonObject().put("path", "my-config.json"));
        ConfigStoreOptions sysPropsStore = new ConfigStoreOptions().setType("sys");
        ConfigRetrieverOptions options = new ConfigRetrieverOptions()
            .setScanPeriod(2000)
            .addStore(fileStore); //.addStore(sysPropsStore);

        ConfigRetriever retriever = ConfigRetriever.create(vertx, options);

        retriever.getConfig(ar -> {
            if (ar.failed()) {
                // Failed to retrieve the configuration
                ar.cause().printStackTrace();
            } else {
                JsonObject config = ar.result();
                vertx.deployVerticle("test.vertx.app.HttpVerticle", new DeploymentOptions().setConfig(config));
                System.out.println("Loaded Config is : " + config);
            }
        });

        retriever.listen(change -> {
            JsonObject json = change.getNewConfiguration();
            System.out.println("New configuration detected " + json);
        });


    }
}
