/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("test.vertx.java-application-conventions")
}

dependencies {
    val vertxVersion = "4.0.0"

    implementation("ch.qos.logback:logback-classic:1.2.3")
    implementation("com.fasterxml.jackson.core:jackson-databind:2.12.0")
    implementation("com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.12.0")

    implementation(project(":model"))
    implementation(project(":weather-scrap"))
    implementation("io.vertx:vertx-config:${vertxVersion}")
    implementation("io.vertx:vertx-web:${vertxVersion}")

    implementation("com.fasterxml.jackson.core:jackson-databind:2.12.0")
}

application {
    // Define the main class for the application.
    mainClass.set("test.vertx.app.App")
}
