/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("test.vertx.java-application-conventions")
}

dependencies {
    implementation(project(":utilities"))
    implementation("io.vertx:vertx-config:4.0.0")

}

application {
    // Define the main class for the application.
    mainClass.set("test.vertx.app.App")
}
