/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("test.vertx.java-application-conventions")
}

dependencies {
    val vertxVersion = "4.0.0"

    implementation(project(":model"))
    implementation(project(":weather-scrap"))
    implementation("io.vertx:vertx-config:${vertxVersion}")
    implementation("io.vertx:vertx-web:${vertxVersion}")
}

application {
    // Define the main class for the application.
    mainClass.set("test.vertx.app.App")
}
